apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: dev-deployer
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create","update","delete","get","list"]
